### PR TITLE
existing anime import ikaros database for file manager

### PR DESCRIPTION
**Pull request by li-guohao**
- [x] Update the [`CHANGES` log](https://github.com/ikaros-dev/ikaros/blob/develop/CHANGELOG.MD).
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Closes #<issue number>.

### CODE REVIEW

**Comment by li-guohao** [comment]
@DDSRem dockerfile文件有更新，增加了一个导入目录方便导入已经存在的资源，麻烦帮忙review下dockerfile，看下是否有问题。

**Review by DDSRem — COMMENTED** [review]
Dockerfile review passed

**Comment by li-guohao** [comment]
> 加了一个导入目录方便导入已经存在的资源

好多谢谢

**Comment by li-guohao** [comment]
> Dockerfile review passed

好的，谢谢

**Pull request merged**
